### **Introduction**

In today’s digital world, users have access to countless movies and TV shows on streaming platforms. Choosing the right content from such large collections can be challenging. Recommendation systems help by providing personalized suggestions, making it easier for users to find what they like.

A **Movie Recommendation System** uses machine learning to analyze user preferences, past activity, and movie details to suggest movies that match their interests. Platforms like Netflix and Amazon Prime use these systems to improve user experience and engagement.

This project focuses on building a movie recommendation system using techniques like Content-Based Filtering and Collaborative Filtering. It aims to:
1. Analyze movie data to identify important features.
2. Recommend movies based on user preferences.
3. Evaluate the system’s accuracy and performance.

The goal is to show how machine learning can make data-driven recommendations and improve the movie selection process for users.

there are three types of recommendation systems

**1)content based recommendation system.** : recomends movies to users based on the movies or content they have watched before.

**2)popularity based recommendation system.** : suggests movies which are very popular. example,top 10 movies in UK on Amazon Prime and Netflix.

**3)collobarative recommendation system.** : Groups peoples based on their watching pattern.that is peoples with same taste in movies will be recommended same movies. example, if person A and person B likes movie Star wars and person B likes the movie say xyz then recommendation system will suggest movie xyz to person A.(of course data there is not only two records,its greater in volume😂.)

The steps to follow in this project are outlined below:

**1)Data Collection:** Gather movie-related data such as titles, genres, and descriptions.

**2)Data Preprocessing:** Clean and organize the data to make it suitable for analysis.

**3)Feature Extraction:** Convert textual data (e.g., genres, descriptions) into numerical data (feature vectors).

**4)Calculate Similarity Scores:** Compute similarity scores between movies to determine how similar they are. This is achieved using a similarity measure, such as cosine similarity.

**5)User Input:** Allow the user to input a movie name.
Using the cosine similarity algorithm, which measures the similarity between vectors, the system identifies movies similar to the one entered by the user. Based on this comparison, the system generates a list of recommended movies for the user.

**IMPORTING NECESSARY LIBRARIES AND DEPENDENCIES**

**Spell Correction with `difflib`:**  
When a user provides input (like a movie name), there is a possibility of spelling mistakes. To handle this, we use `difflib.get_close_matches()` to find the closest match for the user's input from the movie titles available in our dataset. This helps us retrieve the most relevant movie despite minor errors in the input.

**Vectorizer Feature:**  
The vectorizer feature is used to transform textual data (like movie titles or descriptions) into numerical data, called feature vectors. These vectors represent the text in a way that makes it suitable for machine learning algorithms.

**Cosine Similarity:**  
Cosine similarity calculates a confidence score that measures how similar two movies are based on their feature vectors. This score helps us recommend movies that are closely related to the user's input or preferences.


In [35]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

**Data collection and Preprocessing**

In [36]:
#loading data from csv file to pandas dataframe
movies_data = pd.read_csv('/content/movies.csv')

In [37]:
#print first five rows and last five rows of dataset
movies_data.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [38]:
print last five rows and last five rows of dataset
movies_data.tail()

index  budget                         genres  \
4798   4798  220000          Action Crime Thriller   
4799   4799    9000                 Comedy Romance   
4800   4800       0  Comedy Drama Romance TV Movie   
4801   4801       0                            NaN   
4802   4802       0                    Documentary   

                                               homepage      id  \
4798                                                NaN    9367   
4799                                                NaN   72766   
4800  http://www.hallmarkchannel.com/signedsealeddel...  231617   
4801                        http://shanghaicalling.com/  126186   
4802                                                NaN   25975   

                                               keywords original_language  \
4798  united states\u2013mexico barrier legs arms pa...                es   
4799                                                NaN                en   
4800  date love at first sight narration investigati...                en   
4801                                                NaN                en   
4802               obsession camcorder crush dream girl                en   

                 original_title  \
4798                El Mariachi   
4799                  Newlyweds   
4800  Signed, Sealed, Delivered   
4801           Shanghai Calling   
4802          My Date with Drew   

                                               overview  popularity  ...  \
4798  El Mariachi just wants to play his guitar and ...   14.269792  ...   
4799  A newlywed couple's honeymoon is upended by th...    0.642552  ...   
4800  "Signed, Sealed, Delivered" introduces a dedic...    1.444476  ...   
4801  When ambitious New York attorney Sam is sent t...    0.857008  ...   
4802  Ever since the second grade when he first saw ...    1.929883  ...   

     runtime                               spoken_languages    status  \
4798    81.0  [{"iso_639_1": "es", "name": "Espa\u00f1ol"}]  Released   
4799    85.0                                             []  Released   
4800   120.0       [{"iso_639_1": "en", "name": "English"}]  Released   
4801    98.0       [{"iso_639_1": "en", "name": "English"}]  Released   
4802    90.0       [{"iso_639_1": "en", "name": "English"}]  Released   

                                                tagline  \
4798  He didn't come looking for trouble, but troubl...   
4799  A newlywed couple's honeymoon is upended by th...   
4800                                                NaN   
4801                           A New Yorker in Shanghai   
4802                                                NaN   

                          title vote_average vote_count  \
4798                El Mariachi          6.6        238   
4799                  Newlyweds          5.9          5   
4800  Signed, Sealed, Delivered          7.0          6   
4801           Shanghai Calling          5.7          7   
4802          My Date with Drew          6.3         16   

                                                   cast  \
4798  Carlos Gallardo Jaime de Hoyos Peter Marquardt...   
4799  Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...   
4800  Eric Mabius Kristin Booth Crystal Lowe Geoff G...   
4801  Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...   
4802  Drew Barrymore Brian Herzlinger Corey Feldman ...   

                                                   crew          director  
4798  [{'name': 'Robert Rodriguez', 'gender': 0, 'de...  Robert Rodriguez  
4799  [{'name': 'Edward Burns', 'gender': 2, 'depart...      Edward Burns  
4800  [{'name': 'Carla Hetland', 'gender': 0, 'depar...       Scott Smith  
4801  [{'name': 'Daniel Hsia', 'gender': 2, 'departm...       Daniel Hsia  
4802  [{'name': 'Clark Peterson', 'gender': 2, 'depa...  Brian Herzlinger  

[5 rows x 24 columns]

all columns in the table are self explnatory which tells about the movies description and features

**Summary of Dataset.**

In [39]:
movies_data.describe()

index        budget             id   popularity       revenue  \
count  4803.000000  4.803000e+03    4803.000000  4803.000000  4.803000e+03   
mean   2401.000000  2.904504e+07   57165.484281    21.492301  8.226064e+07   
std    1386.651002  4.072239e+07   88694.614033    31.816650  1.628571e+08   
min       0.000000  0.000000e+00       5.000000     0.000000  0.000000e+00   
25%    1200.500000  7.900000e+05    9014.500000     4.668070  0.000000e+00   
50%    2401.000000  1.500000e+07   14629.000000    12.921594  1.917000e+07   
75%    3601.500000  4.000000e+07   58610.500000    28.313505  9.291719e+07   
max    4802.000000  3.800000e+08  459488.000000   875.581305  2.787965e+09   

           runtime  vote_average    vote_count  
count  4801.000000   4803.000000   4803.000000  
mean    106.875859      6.092172    690.217989  
std      22.611935      1.194612   1234.585891  
min       0.000000      0.000000      0.000000  
25%      94.000000      5.600000     54.000000  
50%     103.000000      6.200000    235.000000  
75%     118.000000      6.800000    737.000000  
max     338.000000     10.000000  13752.000000

**Size of Dataset**

In [40]:
movies_data.shape

(4803, 24)

**Feature Selection**

here i have selected a couple of features from orignal dataset which i think are important accourding to me.

In [41]:
selected_feature = ['genres','keywords','overview','popularity','runtime','vote_average','cast']
print(selected_feature)

['genres', 'keywords', 'overview', 'popularity', 'runtime', 'vote_average', 'cast']


**Data Preprocessing : Replacing null values**

: here we Replace null values with null string

In [42]:
for feature in selected_feature:
  movies_data[feature] = movies_data[feature].fillna('')

In [43]:
#concatinating all the above selected features
combined_features = movies_data['genres']+ ' ' + ['keywords'] +' ' + ['overview'] +' ' + ['popularity'] +' ' + ['runtime'] +' ' +['vote_average']+' ' + [ 'cast']

In [15]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction keywo...
1       Adventure Fantasy Action keywords overview pop...
2       Action Adventure Crime keywords overview popul...
3       Action Crime Drama Thriller keywords overview ...
4       Action Adventure Science Fiction keywords over...
                              ...                        
4798    Action Crime Thriller keywords overview popula...
4799    Comedy Romance keywords overview popularity ru...
4800    Comedy Drama Romance TV Movie keywords overvie...
4801     keywords overview popularity runtime vote_ave...
4802    Documentary keywords overview popularity runti...
Name: genres, Length: 4803, dtype: object


Feature Extraction : converting textual data into numerical data

In [44]:
vectorizer = TfidfVectorizer()

In [45]:
feature_vector = vectorizer.fit_transform(combined_features)

In [46]:
print(feature_vector)

  (0, 0)	0.3361688793558731
  (0, 1)	0.3885006533937732
  (0, 9)	0.4765434780479515
  (0, 22)	0.44372057293815037
  (0, 10)	0.44372057293815037
  (0, 14)	0.13855693576893982
  (0, 18)	0.13855693576893982
  (0, 19)	0.13855693576893982
  (0, 21)	0.13855693576893982
  (0, 25)	0.13855693576893982
  (0, 3)	0.13855693576893982
  (1, 0)	0.4317585091186709
  (1, 1)	0.49897082449251573
  (1, 9)	0.6120486286727272
  (1, 14)	0.17795560413050396
  (1, 18)	0.17795560413050396
  (1, 19)	0.17795560413050396
  (1, 21)	0.17795560413050396
  (1, 25)	0.17795560413050396
  (1, 3)	0.17795560413050396
  (2, 0)	0.45578684532767816
  (2, 1)	0.5267396778588691
  (2, 14)	0.18785923543369032
  (2, 18)	0.18785923543369032
  (2, 19)	0.18785923543369032
  :	:
  (4799, 20)	0.6453049454156126
  (4800, 14)	0.08897225250483574
  (4800, 18)	0.08897225250483574
  (4800, 19)	0.08897225250483574
  (4800, 21)	0.08897225250483574
  (4800, 25)	0.08897225250483574
  (4800, 3)	0.08897225250483574
  (4800, 7)	0.15458125673847745

**Cosine Similarity for Similarity Score in Movie Datasets**


Cosine Similarity is a metric used to measure how similar two vectors are by calculating the cosine of the angle between them. It's commonly used in text-based recommendation systems (like movies) to compare feature vectors derived from textual data, such as movie plots, genres, or cast.


### Steps to Calculate Similarity Score Using Cosine Similarity:

1. **Convert Text Data to Numerical Vectors:**
   - Use a vectorizer (e.g., `TfidfVectorizer` or `CountVectorizer`) to transform text data (e.g., movie descriptions or genres) into feature vectors.

2. **Compute Cosine Similarity:**
   - Use `cosine_similarity` from `sklearn` to calculate the pairwise similarity between all feature vectors.

3. **Extract Similarity Scores:**
   - For a given movie, retrieve its similarity scores with all other movies from the similarity matrix.

4. **Sort Similarity Scores:**
   - Sort the similarity scores in descending order to find the most similar movies.

5. **Recommend Movies:**
   - Use the top similarity scores to recommend the most relevant movies to the user.

In [47]:
similarity = cosine_similarity(feature_vector)

In [48]:
print(similarity)

[[1.         0.77860395 0.51403526 ... 0.07396634 0.33939379 0.15509804]
 [0.77860395 1.         0.6602012  ... 0.09499867 0.43590043 0.19920017]
 [0.51403526 0.6602012  1.         ... 0.10028556 0.46015927 0.21028611]
 ...
 [0.07396634 0.09499867 0.10028556 ... 1.         0.21793662 0.09959387]
 [0.33939379 0.43590043 0.46015927 ... 0.21793662 1.         0.45698549]
 [0.15509804 0.19920017 0.21028611 ... 0.09959387 0.45698549 1.        ]]


In [49]:
print(similarity.shape)

(4803, 4803)


user input

In [50]:
movie_name = input('Enter your favourite movie name :')

Enter your favourite movie name :Star wars


Creating a list of all movies presnt in the dataset.

In [54]:
list_of_all_titles = movies_data['title'].tolist()

In [55]:
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

finding the closest match for input move name

In [56]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['Star Wars', 'Star Trek', 'State Fair']


in the above stament our result was a list of matching value so we all want is just one closest match so we use find_close_match[0] to get output which will be the first value in the list.

In [57]:
close_match =  find_close_match[0]
print(close_match)

Star Wars


In [58]:
# finding the index of the movie with title

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

2912


In [60]:
#getting a list of similar movies using similarity score
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.8791509048678514), (1, 0.5538709703576432), (2, 0.5846951408397232), (3, 0.34811126222229555), (4, 1.0), (5, 0.5538709703576432), (6, 0.16550557280592948), (7, 1.0), (8, 0.36313618662706804), (9, 0.5538709703576432), (10, 0.8791509048678514), (11, 0.5353225850503143), (12, 0.5538709703576432), (13, 0.4609951993303836), (14, 0.8791509048678514), (15, 0.36313618662706804), (16, 1.0), (17, 0.5538709703576432), (18, 0.8451504345314118), (19, 0.5538709703576432), (20, 0.5538709703576432), (21, 0.7003754079795707), (22, 0.4310201813376684), (23, 0.4310201813376684), (24, 0.6522949631046558), (25, 0.20301934138920433), (26, 1.0), (27, 0.9383101756758288), (28, 0.9383101756758288), (29, 0.6198075554602759), (30, 0.5538709703576432), (31, 1.0), (32, 0.36313618662706804), (33, 0.9383101756758288), (34, 0.16550557280592948), (35, 1.0), (36, 1.0), (37, 0.36313618662706804), (38, 0.5538709703576432), (39, 1.0), (40, 0.3270990682769192), (41, 0.9383101756758288), (42, 0.15599420092938324), (4

In [61]:
len(similarity_score)

4803

**sorting the movies based on their similarity score**

here we are arranging movies from higher similarity score to lower similarity score .and we use similariy score and x is nothing but similarity_score

In [65]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(4, 1.0), (7, 1.0), (16, 1.0), (26, 1.0), (31, 1.0), (35, 1.0), (36, 1.0), (39, 1.0), (47, 1.0), (51, 1.0), (52, 1.0), (56, 1.0), (59, 1.0), (68, 1.0), (79, 1.0), (85, 1.0), (91, 1.0), (94, 1.0), (101, 1.0), (102, 1.0), (111, 1.0), (158, 1.0), (169, 1.0), (174, 1.0), (182, 1.0), (183, 1.0), (193, 1.0), (207, 1.0), (229, 1.0), (230, 1.0), (233, 1.0), (242, 1.0), (260, 1.0), (400, 1.0), (466, 1.0), (483, 1.0), (495, 1.0), (507, 1.0), (508, 1.0), (511, 1.0), (577, 1.0), (1079, 1.0), (1490, 1.0), (1990, 1.0), (2372, 1.0), (2433, 1.0), (2444, 1.0), (2492, 1.0), (2912, 1.0), (2995, 1.0), (3305, 1.0), (4042, 1.0), (4117, 1.0), (150, 0.9526433159809522), (342, 0.9526433159809522), (27, 0.9383101756758288), (28, 0.9383101756758288), (33, 0.9383101756758288), (41, 0.9383101756758288), (76, 0.9383101756758288), (108, 0.9383101756758288), (122, 0.9383101756758288), (123, 0.9383101756758288), (125, 0.9383101756758288), (127, 0.9383101756758288), (149, 0.9383101756758288), (166, 0.9383101756758288)

In [66]:
# print the name of similar movies based on the index
#in this step we are going to use index of movie similar to title we used in previous step.
print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . John Carter
2 . Avengers: Age of Ultron
3 . The Avengers
4 . Captain America: Civil War
5 . Iron Man 3
6 . Transformers: Revenge of the Fallen
7 . Transformers: Age of Extinction
8 . TRON: Legacy
9 . Star Trek Into Darkness
10 . Pacific Rim
11 . Transformers: Dark of the Moon
12 . Star Trek Beyond
13 . 2012
14 . Iron Man
15 . Iron Man 2
16 . Captain America: The Winter Soldier
17 . Independence Day: Resurgence
18 . Guardians of the Galaxy
19 . X-Men: First Class


Movie Recommendation System

In [69]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<20):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name :  the pursuit of happyness
Movies suggested for you : 

1 . Australia
2 . The Perfect Storm
3 . The Aviator
4 . Ali
5 . Ben-Hur
6 . Cold Mountain
7 . Dreamgirls
8 . Apollo 13
9 . Fight Club
10 . We Are Marshall
11 . Eat Pray Love
12 . Any Given Sunday
13 . A Civil Action
14 . The Soloist
15 . Dragonfly
16 . The Black Dahlia
17 . The Pursuit of Happyness
18 . A Very Long Engagement
19 . Seven Pounds
